---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - ---centos-8
      - debian-9
      - debian-10
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
